#!/usr/bin/env python3
"""Validator: blocks commits / PRs that change code without a valid amendment record.

Validates that:
1. Every changed code-like file is covered by an amendment's updated_files.
2. Each amendment record contains ALL required YAML fields:
   - mode: amend
   - snapshot_used: CLAUDE.md
   - patterns_used: _code_audit/patterns.md
   - integrity_check_done: true
   - primary_files (non-empty list)
   - related_files_considered (list, may be empty)
   - updated_files (list covering all changed code files)
3. Warns (but does not fail) for missing recommended fields.

Modes:
    pre-commit (default):
        Receives staged filenames as positional args from pre-commit.
    ci (--ci or CI=true):
        Runs git diff against origin/main.

Exit codes:
    0  — Valid (or no code files changed).
    1  — Missing/invalid amendment coverage.

All stdlib — no external dependencies.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path, PurePosixPath

# Ensure the scripts directory is importable
sys.path.insert(0, str(Path(__file__).resolve().parent))

from _audit_config import (
    AMENDMENTS_DIR,
    ENFORCED_EXTENSIONS,
    EXCLUDED_FILES,
    EXCLUDED_PREFIXES,
    RECOMMENDED_AMENDMENT_LIST_FIELDS,
    REQUIRED_AMENDMENT_FIELDS,
    REQUIRED_AMENDMENT_LIST_FIELDS,
)

REPO_ROOT = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# YAML frontmatter parser (stdlib-only, handles our constrained format)
# ---------------------------------------------------------------------------

def parse_frontmatter(text: str) -> dict[str, object]:
    """Parse YAML frontmatter from a markdown file.

    Handles the constrained format generated by repo_audit.py:
    - String values (optionally quoted)
    - List values (inline [] or indented - items)
    - Nested list-of-dicts for not_updated_files (path: / reason:)

    Returns a dict of field_name -> value (str or list).
    """
    lines = text.split("\n")

    # Find frontmatter boundaries (--- delimiters)
    boundaries: list[int] = []
    for i, line in enumerate(lines):
        if line.strip() == "---":
            boundaries.append(i)
            if len(boundaries) == 2:
                break

    if len(boundaries) < 2:
        return {}

    fm_lines = lines[boundaries[0] + 1 : boundaries[1]]
    result: dict[str, object] = {}
    current_key: str | None = None
    current_list: list[object] | None = None
    current_dict_item: dict[str, str] | None = None

    for line in fm_lines:
        stripped = line.strip()
        if not stripped:
            continue

        # Check if this is a list item
        if stripped.startswith("- ") and current_key is not None and current_list is not None:
            val_part = stripped[2:].strip()

            # Check if this is a dict-style list item (e.g., "- path: foo")
            if ": " in val_part and not val_part.startswith('"'):
                k, v = val_part.split(": ", 1)
                current_dict_item = {k.strip(): v.strip().strip('"').strip("'")}
                current_list.append(current_dict_item)
            else:
                current_dict_item = None
                val = val_part.strip('"').strip("'")
                current_list.append(val)
            continue

        # Check for continuation of a dict-style list item (indented key: value under a - item)
        if current_dict_item is not None and ":" in stripped and not stripped.startswith("-"):
            # Extra indentation = continuation of dict item
            indent = len(line) - len(line.lstrip())
            if indent >= 6:  # deeply indented = part of dict item
                k, v = stripped.split(": ", 1)
                current_dict_item[k.strip()] = v.strip().strip('"').strip("'")
                continue

        # Check for key: value pair
        if ":" in stripped:
            # Flush previous state
            current_dict_item = None

            colon_idx = stripped.index(":")
            key = stripped[:colon_idx].strip()
            value = stripped[colon_idx + 1 :].strip()

            current_key = key

            # Inline empty list
            if value == "[]":
                current_list = []
                result[key] = current_list
                continue

            # Value on the same line — it's a scalar
            if value:
                result[key] = value.strip('"').strip("'")
                current_list = None
            else:
                # Value on next lines (list)
                current_list = []
                result[key] = current_list

    return result


# ---------------------------------------------------------------------------
# Path classification
# ---------------------------------------------------------------------------

def _normalize(path: str) -> str:
    """Normalize a path to forward-slash POSIX style."""
    return path.replace("\\", "/")


def _is_excluded(path: str) -> bool:
    """Return True if the path is excluded from amendment enforcement."""
    normed = _normalize(path)

    # Excluded by exact name (case-insensitive for CLAUDE.md)
    basename = PurePosixPath(normed).name
    if basename.lower() in {f.lower() for f in EXCLUDED_FILES}:
        return True

    # Excluded by prefix
    for prefix in EXCLUDED_PREFIXES:
        if normed.startswith(prefix):
            return True

    return False


def _needs_amendment(path: str) -> bool:
    """Return True if a changed file requires amendment coverage."""
    normed = _normalize(path)

    if _is_excluded(normed):
        return False

    suffix = PurePosixPath(normed).suffix.lower()
    return suffix in ENFORCED_EXTENSIONS


def _is_amendment_file(path: str) -> bool:
    """Return True if the path is an amendment record."""
    normed = _normalize(path)
    return normed.startswith(str(AMENDMENTS_DIR) + "/")


# ---------------------------------------------------------------------------
# Amendment validation
# ---------------------------------------------------------------------------

def _read_file_content(path: str) -> str | None:
    """Read file content from disk or git staging area."""
    abs_path = REPO_ROOT / path
    if abs_path.exists():
        return abs_path.read_text(encoding="utf-8")

    # Try reading from git staged content
    try:
        return subprocess.check_output(
            ["git", "show", f":{_normalize(path)}"],
            cwd=str(REPO_ROOT),
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _validate_amendment(path: str) -> tuple[set[str], list[str], list[str]]:
    """Validate a single amendment record.

    Returns:
        (covered_files, errors, warnings)
        - covered_files: set of paths listed in updated_files
        - errors: list of validation errors (hard failures)
        - warnings: list of warnings (soft, non-blocking)
    """
    errors: list[str] = []
    warnings: list[str] = []
    covered: set[str] = set()

    content = _read_file_content(path)
    if content is None:
        errors.append(f"Cannot read amendment file: {path}")
        return covered, errors, warnings

    fm = parse_frontmatter(content)

    if not fm:
        errors.append(f"No YAML frontmatter found in: {path}")
        return covered, errors, warnings

    # Check required scalar fields
    for field_name, expected_value in REQUIRED_AMENDMENT_FIELDS:
        actual = fm.get(field_name)
        if actual is None:
            errors.append(f"Missing required field '{field_name}' in: {path}")
        elif expected_value is not None and str(actual) != expected_value:
            errors.append(
                f"Field '{field_name}' must be '{expected_value}', "
                f"got '{actual}' in: {path}"
            )

    # Check required list fields
    for field_name in REQUIRED_AMENDMENT_LIST_FIELDS:
        actual = fm.get(field_name)
        if actual is None:
            errors.append(f"Missing required list field '{field_name}' in: {path}")
        elif not isinstance(actual, list):
            errors.append(f"Field '{field_name}' must be a list in: {path}")

    # Check primary_files is non-empty
    primary = fm.get("primary_files")
    if isinstance(primary, list) and len(primary) == 0:
        errors.append(f"'primary_files' must not be empty in: {path}")

    # Collect updated_files for coverage checking
    updated = fm.get("updated_files")
    if isinstance(updated, list):
        for f in updated:
            if isinstance(f, str):
                covered.add(_normalize(f))

    # Check recommended fields (warnings only)
    for field_name in RECOMMENDED_AMENDMENT_LIST_FIELDS:
        if fm.get(field_name) is None:
            warnings.append(f"Recommended field '{field_name}' missing in: {path}")

    return covered, errors, warnings


# ---------------------------------------------------------------------------
# Main validation logic
# ---------------------------------------------------------------------------

def validate(staged_files: list[str]) -> int:
    """Validate that staged code files have valid amendment coverage.

    Returns 0 on success, 1 on failure.
    """
    normed = [_normalize(f) for f in staged_files]

    code_files = [f for f in normed if _needs_amendment(f)]
    amendment_files = [f for f in normed if _is_amendment_file(f)]

    # No code files changed — nothing to enforce
    if not code_files:
        return 0

    # No amendment files at all — immediate failure
    if not amendment_files:
        _print_no_amendment_error(code_files)
        return 1

    # Validate each amendment and collect coverage
    all_covered: set[str] = set()
    all_errors: list[str] = []
    all_warnings: list[str] = []

    for af in amendment_files:
        covered, errors, warnings = _validate_amendment(af)
        all_covered.update(covered)
        all_errors.extend(errors)
        all_warnings.extend(warnings)

    # Check for structural errors in amendments
    if all_errors:
        print("Amendment protocol violation — invalid amendment record(s)!", file=sys.stderr)
        print("", file=sys.stderr)
        for err in all_errors:
            print(f"  ERROR: {err}", file=sys.stderr)
        print("", file=sys.stderr)
        print("Fix the amendment record(s) and re-stage.", file=sys.stderr)
        return 1

    # Check coverage: every changed code file must be in updated_files
    uncovered = [f for f in code_files if f not in all_covered]

    if uncovered:
        _print_coverage_error(uncovered)
        return 1

    # Print warnings (non-blocking)
    if all_warnings:
        for warn in all_warnings:
            print(f"  WARNING: {warn}", file=sys.stderr)
        print("", file=sys.stderr)

    return 0


def _print_no_amendment_error(code_files: list[str]) -> None:
    """Print error for missing amendment files entirely."""
    print("Amendment protocol violation!", file=sys.stderr)
    print("", file=sys.stderr)
    print("Code files changed but no amendment record is staged:", file=sys.stderr)
    for f in sorted(code_files):
        print(f"  - {f}", file=sys.stderr)
    print("", file=sys.stderr)
    print("Create an amendment with:", file=sys.stderr)
    files_arg = " ".join(f'"{f}"' for f in sorted(code_files))
    print(
        f"  python scripts/repo_audit.py amend "
        f"--slug <name> --description \"<what changed>\" "
        f"--primary <main_file> --files {files_arg}",
        file=sys.stderr,
    )
    print("", file=sys.stderr)
    print("IMPORTANT: Before filling in the amendment, read:", file=sys.stderr)
    print("  1. CLAUDE.md (codebase snapshot)", file=sys.stderr)
    print("  2. _code_audit/patterns.md (pattern lookup table)", file=sys.stderr)


def _print_coverage_error(uncovered: list[str]) -> None:
    """Print error for code files not covered by any amendment."""
    print("Amendment protocol violation — uncovered code files!", file=sys.stderr)
    print("", file=sys.stderr)
    print("These changed code files are not in any amendment's updated_files:", file=sys.stderr)
    for f in sorted(uncovered):
        print(f"  - {f}", file=sys.stderr)
    print("", file=sys.stderr)
    print("Add them to your amendment's updated_files list and re-stage.", file=sys.stderr)


# ---------------------------------------------------------------------------
# CI mode
# ---------------------------------------------------------------------------

def validate_ci() -> int:
    """Validate amendment coverage for a CI/PR context."""
    try:
        diff_output = subprocess.check_output(
            ["git", "diff", "--name-only", "--diff-filter=ACMR", "origin/main...HEAD"],
            cwd=str(REPO_ROOT),
            text=True,
            stderr=subprocess.DEVNULL,
        )
    except subprocess.CalledProcessError:
        print("Warning: Could not run git diff against origin/main. Skipping.", file=sys.stderr)
        return 0

    changed = [_normalize(f.strip()) for f in diff_output.strip().split("\n") if f.strip()]
    if not changed:
        return 0

    return validate(changed)


# ---------------------------------------------------------------------------
# CLI entry
# ---------------------------------------------------------------------------

def main() -> None:
    ci_mode = os.environ.get("CI") == "true" or "--ci" in sys.argv

    if ci_mode:
        sys.argv = [a for a in sys.argv if a != "--ci"]
        sys.exit(validate_ci())
    else:
        # Pre-commit mode: files passed as positional args
        files = [a for a in sys.argv[1:] if not a.startswith("-")]
        if not files:
            # Fallback: get staged files from git
            try:
                output = subprocess.check_output(
                    ["git", "diff", "--cached", "--name-only", "--diff-filter=ACMR"],
                    cwd=str(REPO_ROOT),
                    text=True,
                )
                files = [f.strip() for f in output.strip().split("\n") if f.strip()]
            except (subprocess.CalledProcessError, FileNotFoundError):
                print("Warning: Could not determine staged files. Skipping.", file=sys.stderr)
                sys.exit(0)

        sys.exit(validate(files))


if __name__ == "__main__":
    main()
